### ISSUE TITLE
error when updating esp

### ISSUE THREAD

**Issue by tamimology** [hydazz/docker-esphome#5]
`INFO Reading configuration /config/tv-back-leds.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing tv-back-leds (board: esp01_1m; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
Error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/platformio/cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/platformio/run/cli.py", line 142, in cli
    process_env(
  File "/usr/lib/python3.10/site-packages/platformio/run/cli.py", line 197, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "/usr/lib/python3.10/site-packages/platformio/run/processor.py", line 83, in process
    install_project_env_dependencies(
  File "/usr/lib/python3.10/site-packages/platformio/package/commands/install.py", line 131, in install_project_env_dependencies
    _install_project_env_platform(project_env, options),
  File "/usr/lib/python3.10/site-packages/platformio/package/commands/install.py", line 148, in _install_project_env_platform
    PlatformPackageManager().install(
  File "/usr/lib/python3.10/site-packages/platformio/package/manager/platform.py", line 62, in install
    p.install_required_packages(force=force)
  File "/usr/lib/python3.10/site-packages/platformio/platform/_packages.py", line 76, in install_required_packages
    self.install_package(name, force=force)
  File "/usr/lib/python3.10/site-packages/platformio/platform/_packages.py", line 70, in install_package
    return self.pm.install(spec or self.get_package_spec(name), force=force)
  File "/usr/lib/python3.10/site-packages/platformio/package/manager/_install.py", line 48, in install
    pkg = self._install(spec, skip_dependencies=skip_dependencies, force=force)
  File "/usr/lib/python3.10/site-packages/platformio/package/manager/_install.py", line 71, in _install
    pkg = self.get_package(spec)
  File "/usr/lib/python3.10/site-packages/platformio/package/manager/base.py", line 264, in get_package
    for pkg in self.get_installed():
  File "/usr/lib/python3.10/site-packages/platformio/package/manager/base.py", line 249, in get_installed
    self.load_manifest(pkg).get("system")
  File "/usr/lib/python3.10/site-packages/platformio/package/manager/base.py", line 187, in load_manifest
    result = ManifestParserFactory.new_from_file(item).as_dict()
  File "/usr/lib/python3.10/site-packages/platformio/package/manifest/parser.py", line 76, in new_from_file
    cls.read_manifest_contents(path), type_from_uri, remote_url
  File "/usr/lib/python3.10/site-packages/platformio/package/manifest/parser.py", line 62, in read_manifest_contents
    with io.open(path, encoding=encoding) as fp:
PermissionError: [Errno 13] Permission denied: '/config/.esphome/platformio/packages/tool-scons/package.json'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================`

**Comment by hydazz** [comment]
`chown -r abc:abc /config/.esphome`

**Comment by tamimology** [comment]
I am on vcxpz/esphome:latest. I can see it syays it is moved to hydaz now

Will update from my side and revert back to you

**Comment by hydazz** [comment]
let me know if you get any `xtensa-lx106-elf-g++: Permission denied` errors as well.

**Comment by tamimology** [comment]
It working just fine now after changing the image to hydaz/esphome
